## Tensorflow Denemeleri

Geçtiğimiz haftanın büyük bir bölümünde, Derin Öğrenme modellerinizde tensörler kullandınız. Bugünkü zorluklar boyunca, tensörleri kapsamlı bir şekilde kullanacak ve bazı alışılmadık model mimarileriyle çalışacaksınız. 


Bu ısınma çalışmasında, bazı yeni yöntemlerle tanışacaksınız. 

Buradaki tüm yöntemler, günün ilerleyen saatlerinde karşılaşacağınız zorlukları 100 kat daha kolay hale getirecek, bu nedenle daha sonra takılırsanız, doğru cevapları nasıl bulduğunuzu görmek için buraya geri dönün. 

In [1]:
import tensorflow as tf

2026-06-03 10:31:56.546358: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-06-03 10:31:56.549607: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2026-06-03 10:31:56.555567: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2026-06-03 10:31:56.572555: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:479] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2026-06-03 10:31:56.595131: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:10575] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registe

A) `tf.ones` kullanarak (3,3) şeklinde birler ile doldurulmuş bir tensör `a` oluşturun.

In [3]:
a = tf.ones(shape=(3,3))
a

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

B) tf.expand_dims kullanarak `a`'yı `b` adlı (1,3,3) şekilli bir nesne haline getirin.

In [4]:
b = tf.expand_dims(a,0)
b.shape

TensorShape([1, 3, 3])

In [5]:
b

<tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

C) Boyutu (9,1) olan ve sıfırlarla dolu bir tensör `c` oluşturun.

In [6]:
c = tf.zeros(shape=(9,1))
c

<tf.Tensor: shape=(9, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)>

D) `c`'yi (1, 3, 3) şeklinde yeniden şekillendirin. Adını `d` olarak belirleyin.

In [8]:
d = tf.reshape(c,shape=(1,3,3))
d.shape

TensorShape([1, 3, 3])

E) `tf.matmul` kullanarak `b` ve `d` matrislerini birbiriyle çarpın ve şimdi tensörü `e`'ye atayın. 

In [10]:
e = tf.matmul(b,d)

F) Aşağıda bir `numpy` dizisi bulunmaktadır. Bunu `array_tensor` adlı bir tensöre dönüştürün. Ardından `tf.cast` kullanarak bunun `int` değil `float` türü olduğundan emin olun. Sonucu `f`'ye atayın.

In [11]:
import numpy as np

In [12]:
array = np.array([[
    [1,2,3],
    [1,2,3],
    [4,5,6],
    [7,8,9]
]])

In [13]:
array_tensor = tf.convert_to_tensor(array)
f = tf.cast(array_tensor,float)
f.dtype

tf.float32

In [14]:
f.shape

TensorShape([1, 4, 3])

G) `f`'nin __last column__ değerleri seçin ve bunu `g`'ye kaydedin. Açıkça belirtmek gerekirse, `g`'nin şekli (4,) olmalı ve `3,3,6,9` değerlerini içermelidir. 

In [16]:
g = f[0,:,-1]
g

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([3., 3., 6., 9.], dtype=float32)>

H) g boyutlarını (4,1) şekline gelecek şekilde genişletin. Bunu `h`'ye atayın.

In [17]:
h = tf.expand_dims(g, -1)
h.shape

TensorShape([4, 1])

I) İsteğe bağlı `transpose_b` argümanıyla `tf.matmul` kullanarak e ile f'yi çarpın (konumsal argümanlarınızda önce `e`, sonra `f` gelmelidir). Bunu `i`'ye atayın.

In [18]:
i = tf.matmul(e,f,transpose_b=True)

J) Birlerle dolu bir `(10,10)` tensör oluşturun. Ardından `tf.linalg.band_part()` kullanarak matrisin üst üçgenini maskeleme yapın (yani üst üçgenin tamamı 0 olmalıdır). `j`'ye atayın.

In [19]:
ones = tf.ones((10,10))
j = tf.linalg.band_part(ones,-1,0)

K) Aşağıdaki `number_list`'i alın ve bir tensör haline getirin. Bunu `k`'ye atayın.

In [20]:
number_list = [1,2,3,4,8]

In [21]:
k = tf.convert_to_tensor(number_list)

L) `tf.expand_dims` kullanarak `k`'yi (1,5) şekilli bir tensör haline getirin. `l`'ye atayın.

In [23]:
l = tf.expand_dims(k,0)

M) `tf.tile` kullanarak `l` (okunuşu “L”) 50 kez tekrarlayın, sonuçta `(50, 5)` şeklinde olsun. `m`'ye atayın.

In [24]:
m = tf.tile(l,(50,1))

N) Basit bir Boolean ifadesi kullanarak, `m`'nin 3 olduğu yerler için `True` değerleri ve 3 olmadığı yerler için `False` değerleri içeren bir tensör oluşturun. `n`'ye atayın.

In [25]:
n = m==3

O) Değişkeniniz `m` içindeki her değeri 3'e bölün. `o`'ya atayın.

In [26]:
o = m/3

P) `tf.concat()` kullanarak, aşağıdaki (5,5) ve (5,5) şekilli iki tensörün listesini alın ve bunları (10,5) şekilli son bir tensöre dönüştürün. `p`'ye atayın. Birleştirme eksenini dikkatlice düşünün.

In [27]:
tensor_list = [tf.ones((5,5)), tf.ones((5,5))]

In [28]:
p = tf.concat(tensor_list,axis=0)

### Cevaplarını Kontrol Et

In [29]:
from nbresult import ChallengeResult

result = ChallengeResult(
    "tensors",
    a=a.numpy(),
    b=b.numpy(),
    c=c.numpy(),
    d_shape=tuple(d.shape),
    e=e.numpy(),
    f=f.numpy(),
    g=g.numpy(),
    h=h.numpy(),
    i=i.numpy(),
    j=j.numpy(),
    k=k.numpy(),
    l=l.numpy(),
    m=m.numpy(),
    n=n.numpy(),
    o=o.numpy(),
    p_shape=tuple(p.shape),
)

result.write()
print(result.check())


============================= test session starts ==============================
platform linux -- Python 3.12.9, pytest-8.3.4, pluggy-1.5.0 -- /home/seval/.pyenv/versions/3.12.9/envs/workintech/bin/python
cachedir: .pytest_cache
rootdir: /home/seval/workintech/week_19/S19D2-S-Data-tensor-trials/tests
plugins: anyio-4.8.0, dash-4.1.0, typeguard-4.4.2
collecting ... collected 15 items

test_tensors.py::TestTensors::test_a PASSED                              [  6%]
test_tensors.py::TestTensors::test_b PASSED                              [ 13%]
test_tensors.py::TestTensors::test_c PASSED                              [ 20%]
test_tensors.py::TestTensors::test_d_shape PASSED                        [ 26%]
test_tensors.py::TestTensors::test_e PASSED                              [ 33%]
test_tensors.py::TestTensors::test_f PASSED                              [ 40%]
test_tensors.py::TestTensors::test_g PASSED                              [ 46%]
test_tensors.py::TestTensors::test_i PASSED        

### Harika iş 🔥

Şimdi modellemeye başlama zamanı!